### PR TITLE
Transition from Bamboo to Swoosh?

### PR DESCRIPTION
**Pull request by rktjmp**
Phoenix 1.6 bundles [Swoosh](https://hexdocs.pm/swoosh) as a mailer. Is there any desire to switch Booms internal mailer over?

It would reduce downstream project dependencies and probably feel more "natural" in future Phoenix projects since devs can just pass the application's existing mailer to Boom?

I am aware this might feel a bit like "change for changes sake". I think the only reason to do it would be if you wanted a smoother on-ramp in 1.6+ projects.

Swapping the mailer out is actually pretty painless, mostly a small patch to `MailNotifier.ex` and `Application.ex` (and the patch to `Application.ex` is probably optional).

```elixir
  def notify(error_info, options) do
    # Note, unlike Bamboo, Swoosh will raise while creating the mail if it is
    # invalid (has a bad recipient, etc). To consumers of this function, the
    # behaviour is identical to Bamboo's `deliver_later!`.
    email =
      new()
      |> to(options[:to])
      |> from(options[:from])
      |> subject("#{options[:subject]}: #{hd(error_info) |> Map.get(:reason)}")
      |> html_body(HTMLContent.build(error_info))
      |> text_body(TextContent.build(error_info))

    # Swoosh does not provide async send, but it recommends using Elixir tasks.
    # This is actually identical to Bamboo, Bamboo just wraps the boiler plate.
    # This could also just be Task.start since Boom doesn't seem to care about
    # tracking delivery results?
    Task.Supervisor.start_child(BoomNotifier.AsyncEmailSupervisor, fn ->
      options[:mailer].deliver!(email)
    end)

    # return email to mirror bamboo deliver_later!
    email
  end
```

```elixir
  def start(_type, _args) do
    children = [
      BoomNotifier.ErrorStorage,
      BoomNotifier.NotifierSenderServer,
      {Task.Supervisor, name: BoomNotifier.AsyncEmailSupervisor}
    ]

    Supervisor.start_link(children, strategy: :one_for_one)
  end
```

There's some small patches to the tester since `Swoosh` wont accept a raw `PID` as a valid recipient, but mostly that's it.

As described in the comments, you could just replace the supervisor with `Task.start()` and drop the supervisor if we don't care about tracking task status, which I don't think happens with the Bamboo implementation anyway?

This would be a breaking change as Swoosh and Bamboo are *just* slightly incompatible, Swoosh provides `deliver`, while Bamboo provides `deliver_now|later` and `MailNotifier` makes an assumption on what to call, though that could even be configured with an option if you really wanted.

### CODE REVIEW

**Comment by iaguirre88** [comment]
Hey @rktjmp! I know it's been a while but we've been discussing how to make this change the less disrupted as possible for actual users.

We've come up with the idea of supporting both and letting the user decide which one they want to use.

Something like this:

```elixir
use BoomNotifier,
      notifier: BoomNotifier.MailNotifier.Bamboo,
      options: [
        . . . 
      ]
```

or 

```elixir
use BoomNotifier,
      notifier: BoomNotifier.MailNotifier.Swoosh,
      options: [
        . . . 
      ]
```

So this PR only needs to reorganize the modules: keep the actual code in a new `BoomNotifier.MailNotifier.Bamboo` module and your changes in `BoomNotifier.MailNotifier.Swoosh`


I'll be glad to hear your input about this suggestion so let me know what do you think

**Comment by rktjmp** [comment]
Sounds good, do you want me to submit a PR?

**Comment by iaguirre88** [comment]
@rktjmp That would be great
I've already opened a PR to support multiple email libraries here https://github.com/wyeworks/boom/pull/70

Maybe rebasing this PR with this branch `support-different-email-libraries` and making a few changes is enough to have it working

**Comment by rktjmp** [comment]
Continued in #71

**Pull request closed without merging**
